version: "3"
services:
  solbase:
    image: muellerlab/solbase:1.05
    hostname: sgndev
    depends_on:
      - postgres
      - nginx
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
    volumes:
      - ./solbase/sgn_local.conf:/cxgn/sgn/sgn_local.conf
      - ./solbase/:/export/prod
      - ./solbase/:/data/prod
  postgres:
    image: postgres:9.5
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
